services:
  app:
    container_name: link-saver-bot
    build:
      context: .
      target: development
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  postgres:
    container_name: link-saver-db
    image: postgres:16-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    container_name: link-saver-redis
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
volumes:
  postgres:
  redis:
